apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: pod-failure
  namespace: chaos-mesh
spec:
  action: pod-failure
  mode: one
  value: ""
  duration: "30s"
  selector:
    namespaces:
      - chaos-app
    labelSelectors:
      "app": "server"
  scheduler:
    cron: "@every 1m"
