apiVersion: apps/v1
kind: Deployment
metadata:
  name: reader
  namespace: chaos-app
spec:
  selector:
    matchLabels:
      app: reader
  template:
    metadata:
      labels:
        app: reader
      annotations:
        # Annotation for Litmus
        litmuschaos.io/chaos: "true"
    spec:
      containers:
        - name: reader
          image: iskorotkov/chaos-client
          args:
            - "-host"
            - "server"
            - "-verb"
            - "get"
            - "-rate"
            - "1"
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: writer
  namespace: chaos-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: writer
  template:
    metadata:
      labels:
        app: writer
      annotations:
        # Annotation for Litmus
        litmuschaos.io/chaos: "true"
    spec:
      containers:
        - name: writer
          image: iskorotkov/chaos-client
          args:
            - "-host"
            - "server"
            - "-verb"
            - "post"
            - "-rate"
            - "1"
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  namespace: chaos-app
spec:
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
      annotations:
        # Annotation for Litmus
        litmuschaos.io/chaos: "true"
    spec:
      containers:
        - name: server
          image: iskorotkov/chaos-server
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8811
---
apiVersion: v1
kind: Service
metadata:
  name: server
  namespace: chaos-app
spec:
  selector:
    app: server
  ports:
    - port: 8811
      targetPort: 8811
